theme: minima

minima:
  social_links:
    twitter: stevededoncker
    github: stevededoncker
    instagram: stevededoncker
    linkedin: stevededoncker
  show_excerpts: true
  header_pages:
    - about.md
