title: Steve's blog
author:
  name: Steve De Doncker
  email: noreply@incunabula.be
description: > # this means to ignore newlines until "show_excerpts:"
  Bourgeois bohemian. Dad. Endurance junkie. Living the dotcom dream. Hosted op Github-Pages met Jekyll.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %B %Y"
  
  social_links:
    twitter: stevededoncker
    github:  stevededoncker
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - index.md
# - about.md

permalink: /:title/

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
