title: stevededoncker.github.io
twitter_username: stevededoncker
github_username: stevededoncker
linkedin_username: stevededoncker
theme: jekyll-theme-cayman
plugins:
 - jekyll-feed
 - jekyll-sitemap
