theme: minima
header_pages:
  - about.md
author:
  name: Steve De Doncker
  email: "steve(dot)incunabula(at).be"
minima:
  social_links:
    twitter: stevededoncker
    github: stevededoncker
    stackoverflow: "stevededoncker"
    instagram: stevededoncker
    linkedin: stevededoncker
